## Intelligence Artificielle
### Travaux pratiques n°1 (Calcul scientifique avec NumPy)
### 2022-2023

---



**Importation du module numpy**


In [ ]:
import numpy as np

In [ ]:
print(np.array([1,2,3]).shape)

(3,)


**Exercice 1**

**1)** Créer un tableau unidimensionnel, nommé $vect$, de $12$ **éléments aléatoires** compris entre $0$ et $20$. Afficher $vect$


In [ ]:
t_b=np.random.randint(0,21,12)
print(t_b)

[19  4 16 20  8  8 11 13  5  1 19 16]


**2)** Transformer $vect$ en un tableau 2D, nommée $t\_b$, de taille $4 \times 3$. Afficher $t\_b$


In [ ]:
tb=np.reshape(t_b,(4,3))
print(tb)

[[19  4 16]
 [20  8  8]
 [11 13  5]
 [ 1 19 16]]


In [ ]:
print(tb[0,0])

19


**3)** Afficher la taille, la dimension et le nombre des éléments de $t\_b$


In [ ]:
print(np.shape(tb))
print(np.ndim(tb))
print(np.size(tb))

(4, 3)
2
12


**4)** Afficher le maximum et la somme de chaque ligne de $t\_b$

In [ ]:
print(np.max(tb,axis=1))
print(np.sum(tb,axis=1))

[15 18 15  5]
[34 33 22  8]


**5)** Transformer $t\_b$ en un tableau de taille $4 \times 4$, nommé $t\_a$ . Afficher $t\_a$


In [ ]:
t_sump=np.resize(t_b,[4,4])
print(t_sump)

[[11  8 15  0]
 [18 15  4 15]
 [ 3  3  5  0]
 [11  8 15  0]]


**6)** Décomposer $t\_a$ verticalement en $4$ tableaux $X$, $Y$, $Z$ et $T$ comportant chacun $4$ éléments. Afficher $X$, $Y$, $Z$ et $T$


In [ ]:
x,y,z,t=np.split(t_sump,[1,2,3],axis=1)
print(x,y,z,t,sep="/")
print(y.shape)


[[11]
 [18]
 [ 3]
 [11]]/[[ 8]
 [15]
 [ 3]
 [ 8]]/[[15]
 [ 4]
 [ 5]
 [15]]/[[ 0]
 [15]
 [ 0]
 [ 0]]
(4, 1)


**7)** Fusionner le tableau $X$ et $t\_a$ de sorte que les lignes de $X$ sont ajoutées en tant que nouvelles lignes à $t\_a$


In [ ]:

t_r=np.concatenate([t_sump, x.reshape(1,4)])
print(t_r)

[[11  8 15  0]
 [18 15  4 15]
 [ 3  3  5  0]
 [11  8 15  0]
 [11 18  3 11]]


**8)** 	Définir un tableau 1D, nommé $t\_u$, contenant les éléments de $t\_a$ triés dans l’ordre croissant de sorte que aucun élément ne se répète. Afficher $t\_u$


In [ ]:
t_u=np.unique(t_r)
print(t_u)

[ 0  3  4  5  8 11 15 18]


**9)** Transformer $t\_u$ en un tableau de taille $4 \times 3$. Puis, insérer les éléments de $Y$ à la deuxième colonne de $t\_u$. Afficher $t\_u$


In [ ]:
t_a=np.resize(t_u,(4,3))
t_uu=np.insert(t_a,2,y.ravel(),axis=1)
print(t_uu)

[[ 0  3  8  4]
 [ 5  8 15 11]
 [15 18  3  0]
 [ 3  4  8  5]]


**Exercice 2**

In [ ]:
sales = np.array([[100, 200, 150],
                  [250, 300, 200],
                  [175, 225, 275],
                  [300, 250, 225]])

In [ ]:
print(sales[2:,1])

[225 250]


<font color='blue'>**NB.**Les colonnes de $sales$ représentent les ventes de trois produits différents et les lignes représentent les mois de l’année, de Janvier à Avril </font>

**1)** Calculer la moyenne globale des ventes

In [ ]:
print(np.mean(sales))

220.83333333333334


**2)** Calculer la somme des ventes pour chaque produit, en excluant le mois de Janvier

In [ ]:
print(np.sum(sales[1:],axis=1))

[750 675 775]


**3)** Calculer la somme des ventes pour chaque produit pour les mois où les ventes ont été supérieures à la moyenne globale

In [ ]:
s_v=np.sum(np.where(sales>np.mean(sales),sales,0),axis=0)
print(s_v)

[550 775 500]


**4)**	Créer un tableau de booléens indiquant si chaque vente est supérieure ou égale à $200$

In [ ]:
t=np.where(sales>200,True,False)
print(t)
tt=sales>200
print(tt)

[[False False False]
 [ True  True False]
 [False  True  True]
 [ True  True  True]]
[[False False False]
 [ True  True False]
 [False  True  True]
 [ True  True  True]]


**5)**	Mélanger les ventes du deuxième produit. Afficher $sales$ après la modification

In [ ]:
np.random.shuffle(sales[:,1])
print(sales)

[[100 250 150]
 [250 200 200]
 [175 225 275]
 [300 300 225]]


**6)** 	Afficher la position du plus grand élément de $sales$ sous forme d’un tuple (**ligne**, **colonne**)

In [ ]:
max=np.argmax(sales)
print(max)
maxpos=np.unravel_index(max,sales.shape)
print(maxpos)

9
(3, 0)


In [ ]:
a=np.array([1,2,3,4])
print(a[2],a[:2],a[1:2],a[1:],a[1:4:2],a[::2],sep=" - ")
print(a[-1])# Accès au dernier élément
b=np.array([[5,6,7,8], [9,10,11,12]]) ; print("b=\n",b)
print("b[:,0]=\n", b[:,0]) # Accès à la première colonne
print("b[1,:]=\n", b[1,:]) # Accès à la deuxième ligne
print("b[1,[0,2]]=\n", b[1,[0,2]]) # Accès à la ligne d’indice 1, et colonnes d’indices 0 et 2
print("b[:2, 1:3]=\n", b[:2,1:3]) # Accès aux lignes d’indices 0 et 1, et colonnes d’indices 1, 2
print("b[:2, :3]=\n", b[:2,:3])
print("b[::2, ::2]=\n",b[::2,::2])
print("Diagonale de b= \n",np.diag(b)) # Renvoie un tableau unidimensionnel avec les éléments de
c=np.array([[5,6,7], [9,10,11], [13,14,15]])
print("Diagonale de c= \n",np.diag(c)) # Renvoie un tableau unidimensionnel avec les éléments de


3 - [1 2] - [2] - [2 3 4] - [2 4] - [1 3]
4
b=
 [[ 5  6  7  8]
 [ 9 10 11 12]]
b[:,0]=
 [5 9]
b[1,:]=
 [ 9 10 11 12]
b[1,[0,2]]=
 [ 9 11]
b[:2, 1:3]=
 [[ 6  7]
 [10 11]]
b[:2, :3]=
 [[ 5  6  7]
 [ 9 10 11]]
b[::2, ::2]=
 [[5 7]]
Diagonale de b= 
 [ 5 10]
Diagonale de c= 
 [ 5 10 15]
